spring:
  main:
    banner-mode: "console"
  application:
    name: tech-challenge-grupo01
  datasource:
    platform: h2
    url: ${DATABASE_URL:jdbc:h2:file:./db/main/tech-challenge-grupo-01}
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: public
  h2:
    console.enable: true


server:
  port: 8080
  servlet:
    context-path: /tech-challenge-grupo01

arsenal:
  library:
    core:
      api:
        enable-docs: true
        docs-base-package: br.com.fiap.techchallengegrupo01.controller