version: '3.1'

services:
  db:
    image: mysql
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_tech_challenge


  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80

volumes:
  dbbase: